# Generated by Django 3.2.6 on 2021-08-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210818_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='laravel2',
            field=models.BooleanField(default=False),
        ),
    ]
