# Generated by Django 3.2.6 on 2021-08-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_project_laravel2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='laravel2',
        ),
    ]
