# Generated by Django 3.2.6 on 2021-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_action_timeline_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('selectors', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='comment',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='status',
            field=models.IntegerField(choices=[(1, 'Descargada'), (2, 'Actualizada'), (3, 'Rechazada'), (4, 'Asignada'), (5, 'Postulada')], default=1),
        ),
    ]
